no_lives = int(input("Please enter number of lives.\n"))
print()
energy_level = int(input("Please enter the energy level.\n"))
print()
shield_level = int(input("Please enter the shield level.\n"))
print()

print("Health has been set.")
print(f"Lives: {'❤'*no_lives}")
print(f"Energy: {'♦'*energy_level}")
print(f"Shield: {'♦'*shield_level}")
